arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - elbow_joint 
     - shoulder_lift_joint 
     - shoulder_pan_joint 
     - wrist_1_joint 
     - wrist_2_joint 
     - wrist_3_joint 
  constraints: 
    shoulder_pan_joint: {goal: 0.05}
    shoulder_lift_joint: {goal: 0.05}
    elbow_joint: {goal: 0.05}
    wrist_1_joint: {goal: 0.05}
    wrist_2_joint: {goal: 0.05}
    wrist_3_joint: {goal: 0.05}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - gripper_finger1_joint
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

